---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo-git
  annotations:
    fluxcd.io/automated: "false"
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 10m
  releaseName: ghost
  targetNamespace: demo-git
  chart:
    spec:
      chart: charts/ghost
  values:
    image:
      repository: bitnami/ghost
      tag: 3.1.1-debian-9-r0
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: ClusterIP
    mariadb:
      master:
        persistence:
          enabled: false
