apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: demo-git
  annotations:
    fluxcd.io/automated: "true"
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 10m
  releaseName: podinfo-prod
  chart:
    spec:
      chart: charts/podinfo
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 4.0.6
    replicaCount: 3
